# Base image
FROM python:3.10-slim

# Install curl and other required tools
RUN apt-get update -y && apt-get install -y curl build-essential

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
   

# Add Poetry to PATH
ENV PATH="/root/.local/bin:$PATH"

# Set working directory
WORKDIR /app

# Copy project files (including poetry.lock and pyproject.toml first for caching)
COPY pyproject.toml poetry.lock* ./

# Copy the rest of the app
COPY . /app

# Install dependencies
RUN poetry install --no-interaction --no-ansi

#Make prestart executable
RUN chmod +x ./prestart.sh




# Run prestart script
RUN poetry run bash ./prestart.sh

# Expose the app port
EXPOSE 8000

# Start the server

CMD ["sh", "-c", "poetry run bash ./prestart.sh && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]

